# Experiment #2
### NORMALIZATION PROBLEM

In [32]:
import numpy as np

# creates a random 5-by-5 array and stores it in X
X = np.random.random((5,5))
print("X:\n", X)

# normalizes the array X and stores it in normalized_X
X_normalized = (X - X.mean())/X.std()
print("\nX_normalized:\n" , X_normalized)

np.save('X_normalized',X_normalized)

X:
 [[0.99880573 0.4104488  0.85647224 0.98683974 0.09630471]
 [0.94907674 0.8672767  0.72357967 0.83752725 0.69976926]
 [0.16190384 0.50838642 0.06851914 0.52529925 0.2415484 ]
 [0.02700521 0.1918537  0.5458509  0.10979194 0.6638459 ]
 [0.8519381  0.91801335 0.35501908 0.11525813 0.58705271]]

X_normalized:
 [[ 1.43629169 -0.37358968  0.99845078  1.39948236 -1.33994786]
 [ 1.28331725  1.03168705  0.58965168  0.94017293  0.516407  ]
 [-1.1381543  -0.07231766 -1.42542079 -0.02029105 -0.89315472]
 [-1.55312436 -1.04602366  0.04292914 -1.29845895  0.4059009 ]
 [ 0.98450304  1.18776122 -0.54410049 -1.28164408  0.16967259]]


### DIVISIBLE BY 3 PROBLEM

In [29]:
import numpy as np

# creates an array, x that consists of positive integers from 1 to 100
A = np.linspace(1,100,100,dtype=int)

# squares each element of the array and stores it back into x
A = A ** 2

# reshapes the array x into a 10-by-10 array
A = A.reshape(10,10)
print("A:\n", x,"\n")

# checks for the elements in array x that is divisible by 3 through modulus operation and stores it in the div_by_3 array
div_by_3 = A[A % 3 ==0]
print("div_by_3:\n", div_by_3)

# Saves the resulting array into 'div_by_3.npy'
np.save('div_by_3', div_by_3)

A:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]] 

div_by_3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
